/**
 * @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		a11yhelp: 1,
		basicstyles: 1,
		clipboard: 1,
		colorbutton: 1,
		colordialog: 1,
		contextmenu: 1,
		elementspath: 1,
		list: 1,
		indentlist: 1,
		enterkey: 1,
		entities: 1,		
		floatingspace: 1,
		format: 1,
		font: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		iframedialog: 1,
		image: 1,
		justify: 1,
		link: 1,
		magicline: 1,
		mergefield: 1,
		maximize: 1,
		ngen_filebrowse: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		resize: 1,
		showborders: 1,
		sharedspace: 1,
		showblocks: 1,
		sourcearea: 1,
		sourcedialog: 1,
		specialchar: 1,
		tab: 1,
		table: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		wysiwygarea: 1
	},
	languages : { 'en' : 1 }
};
